# run: conda env create --file environment.yml
name: report_env
channels:
  - conda-forge
  - defaults
dependencies:
- python==3.7.10
- altair_saver
- matplotlib
- numpy
- pip:
  - jupyter-book
  - dataframe_image
